<?php
/**
 * News template for separate item
 *
 */
/**
 * @var $this Neklo_Blog_Block_Item
 * @see Neklo_Blog_Block_Item
 */
?>

<?php $_newsItem = $this->helper('neklo_blog/config')->getNewsItemInstance(); ?>
<div id="news_item_messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<block type="page/html_breadcrumbs" name="breadcrumbs" as="breadcrumbs"/>

<div class="page-title">
    <h1><?php echo $this->escapeHtml($_newsItem->getTitle()) ?></h1>

    <div class="news_item_subtitle">
        <?php echo $this->formatDate($_newsItem->getTimePublished(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM) ?> |
        <?php echo $this->escapeHtml($_newsItem->getAuthor()) ?>
    </div>
</div>

<div class="news_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_newsItem, 400)): ?>
        <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_newsItem->getTitle()) ?>" /></p>
    <?php endif; ?>

    <div class="news_item_content"><?php echo $_newsItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo Mage::helper('neklo_blog/config')->__('Return to list') ?>
        </a>
    </div>
</div>