<?php
/**
 * News template for items list
 *
 */
/**
 * @var $this Neklo_Blog_Block_List
 * @see Neklo_Blog_Block_List
 */
?>
    <div id="news_list_messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
    <div class="page-title">
        <h1><?php echo Mage::helper('neklo_blog/config')->__('Blog News') ?></h1>
    </div>

    <div class="news_list_view">
        <?php foreach ($this->getCollection() as $newsItem): ?>
            <div id="item_<?php echo $newsItem->getId() ?>" class="news_list_item">
                <h2>
                    <a href="<?php echo $this->getItemUrl($newsItem) ?>">
                        <?php echo $this->escapeHtml($newsItem->getTitle()) ?>
                    </a>
                </h2>

                <div class="news_item_subtitle">
                    <?php echo $this->formatDate($newsItem->getTimePublished(), 'medium') ?> |
                    <?php echo $this->escapeHtml($newsItem->getAuthor()) ?>
                </div>

                <?php if ($imageUrl = $this->getImageUrl($newsItem, 100)): ?>
                    <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($newsItem->getTitle()); ?>" /></p>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>

<?php echo $this->getPager() ?>